In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [6]:
df = pd.read_excel('gepatit.xlsx')
df.head()

,Ф.И.О,yoshi,Пол,В/ДНК,qHBsAg,РНК,гемоглабин,Эритроцит,ранг курсаткич,Тромбоцит,...,Билирубин,креатинин,Мачевина,УЗИ,белок,Фиброскан,альбумин,ПВТ,ШФ,КЛАСС
0,Очилова З,65,2,2,870.0,2,110.0,3.5,0.9,431.0,...,7.49,65.0,5.8,2,75.0,999.0,33.0,1,235.0,1
1,Гайбуллаева Г,25,2,2,53000.0,1,102.0,3.6,0.9,270.0,...,16.25,75.0,6.5,1,65.0,999.0,35.0,1,175.0,1
2,Рахимова Пардахол,62,2,2,0.0,2,94.0,3.3,0.9,181.0,...,19.30,80.0,7.5,1,72.0,999.0,32.0,1,157.0,1
3,Мухамаедова М,31,2,2,0.0,2,102.0,3.4,0.9,182.0,...,10.32,78.0,5.9,1,68.0,999.0,31.0,1,192.0,1
4,Успанова Ф,36,2,2,0.0,2,100.0,3.2,0.9,220.0,...,18.00,70.0,6.8,1,75.0,999.0,32.0,1,185.0,1

In [7]:
df.drop(['Ф.И.О'], axis=1, inplace=True)
df.head()

,yoshi,Пол,В/ДНК,qHBsAg,РНК,гемоглабин,Эритроцит,ранг курсаткич,Тромбоцит,Лейкоцит,...,Билирубин,креатинин,Мачевина,УЗИ,белок,Фиброскан,альбумин,ПВТ,ШФ,КЛАСС
0,65,2,2,870.0,2,110.0,3.5,0.9,431.0,5.7,...,7.49,65.0,5.8,2,75.0,999.0,33.0,1,235.0,1
1,25,2,2,53000.0,1,102.0,3.6,0.9,270.0,7.0,...,16.25,75.0,6.5,1,65.0,999.0,35.0,1,175.0,1
2,62,2,2,0.0,2,94.0,3.3,0.9,181.0,7.1,...,19.30,80.0,7.5,1,72.0,999.0,32.0,1,157.0,1
3,31,2,2,0.0,2,102.0,3.4,0.9,182.0,5.0,...,10.32,78.0,5.9,1,68.0,999.0,31.0,1,192.0,1
4,36,2,2,0.0,2,100.0,3.2,0.9,220.0,7.0,...,18.00,70.0,6.8,1,75.0,999.0,32.0,1,185.0,1

In [15]:
df.drop(['УЗИ', 'Фиброскан', 'ПВТ'], axis=1, inplace=True)

In [14]:
for i in df.columns:
    print(i, len(df[i].value_counts()))

yoshi 51
Пол 2
В/ДНК 50
qHBsAg 159
РНК 6
гемоглабин 58
Эритроцит 50
ранг курсаткич 7
Тромбоцит 122
Лейкоцит 103
с/я 42
моноцит 26
лимфоцит 36
ЭЧТ 39
АЛТ 158
АСТ 138
Билирубин 139
креатинин 174
Мачевина 59
УЗИ 9
белок 115
Фиброскан 43
альбумин 80
ПВТ 2
ШФ 178
КЛАСС 3